package proyectologica2;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.util.ArrayList;
public class GuiCompra extends javax.swing.JFrame {
    static int t=0;
    static double tp=0;
    static ArrayList<Producto>productoComprado=new ArrayList();
    static ArrayList<String>unidadesCompradas=new ArrayList();
    
    DefaultTableModel mtablas=new DefaultTableModel();

    /**
     * Creates new form guiregistrarcompras
     */
    public GuiCompra() {
        initComponents();
        setModelo();
        
        //Ciclo para llenar combobox de clientes
        for (int i = 0; i < GuiPrincipal.controlador.getArregloClientes().size(); i++) {
            id.addItem(GuiPrincipal.controlador.getArregloClientes().get(i).getID());
        }
        
        //Ciclo para llenar combobox de productos
        for (int i = 0; i < GuiPrincipal.controlador.getArregloProductos().size(); i++) {
            codigo.addItem(GuiPrincipal.controlador.getArregloProductos().get(i).getCodigo());
        }
        
    }
    //Configurar la Tabla
    private void setModelo(){
        String cabecera[]={"Codigo","Marca","Cantidad","Precio"};
        mtablas.setColumnIdentifiers(cabecera);
        mtabla.setModel(mtablas);
    }
    
    private void setDatos(){
        Object datos[]=new Object[mtablas.getColumnCount()];
        mtablas.setRowCount(0);
        for (int i = 0; i < productoComprado.size(); i++) {
            datos[0]=productoComprado.get(i).getCodigo();
            datos[1]=productoComprado.get(i).getMarca();
            datos[2]=unidadesCompradas.get(i);
            datos[3]=productoComprado.get(i).getPrecio();
            mtablas.addRow(datos);
        }
        mtabla.setModel(mtablas);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        registrarProducto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        totalapagar = new javax.swing.JTextField();
        facturar = new javax.swing.JButton();
        cancelarCompra = new javax.swing.JButton();
        id = new javax.swing.JComboBox<>();
        codigo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        mtabla = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        unidades = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Compras");

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha");

        fecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DD/MM");

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Documento del cliente");

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Unidades a comprar:");

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Codigo del producto");

        registrarProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registrarProducto.setText("Registrar producto");
        registrarProducto.setActionCommand("Registrar ");
        registrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarProductoActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total:");

        total.setEditable(false);
        total.setBackground(new java.awt.Color(255, 255, 255));
        total.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total a Pagar:");

        totalapagar.setEditable(false);
        totalapagar.setBackground(new java.awt.Color(255, 255, 255));
        totalapagar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalapagarActionPerformed(evt);
            }
        });

        facturar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        facturar.setText("Facturar");
        facturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturarActionPerformed(evt);
            }
        });

        cancelarCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cancelarCompra.setText("Cancelar compra");
        cancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCompraActionPerformed(evt);
            }
        });

        id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        codigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mtabla.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(mtabla);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Cantidad");

        unidades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(totalapagar)))
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)))
                            .addComponent(cancelarCompra))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(facturar)
                        .addGap(87, 87, 87))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(id, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(36, 36, 36)
                                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addComponent(registrarProducto)
                        .addContainerGap(378, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarProducto)
                    .addComponent(jLabel5)
                    .addComponent(unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(totalapagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(facturar)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelarCompra)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalapagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalapagarActionPerformed

    private void registrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarProductoActionPerformed
        Cliente c; //Este cliente sera el que buscaremos en base a lo que se escoja en el combobox de clientes
        Producto p; //Lo mismo con este producto 
        if (GuiPrincipal.controlador.restaUnidades(Integer.parseInt(unidades.getText()),codigo.getSelectedItem().toString())>0){//La funcion de este if es no permitir que se compren mas unidades de las que ahy en stock 
            facturar.setEnabled(true);//activa el boton facturar
            if (GuiPrincipal.controlador.restaUnidades(Integer.parseInt(unidades.getText()),codigo.getSelectedItem().toString())<=10){//Salta una alarma si el producto tiene menos de 10 unidades
            JOptionPane.showMessageDialog(rootPane,"Advertencia: pocas Unidades");
            }    
            p=GuiPrincipal.controlador.buscarProducto(codigo.getSelectedItem().toString());//metodo para bsucar el producto seleccionado en el combobox
            t+=p.getPrecio()*Integer.parseInt(unidades.getText());//suma el valor del producto en base a las unidades comporadas
            total.setText(Integer.toString(t));//actualiza el cuadrode texto con el valor calculado
            c=GuiPrincipal.controlador.buscarCliente(id.getSelectedItem().toString());//Busca al cliente en base a lo escojido en la combobox  
            //Verificamos si la fecha del dia de la compra es igual al dia de nacimiento, si lo es, se hara el descuento del 20%, sino,no y el total a pagar es el 20% del total
            if(fecha.getText().equalsIgnoreCase(c.getFechanacimiento())){
                tp=t*0.8;
            }else{
                tp=t;
            }
            //Agregamos el total a pagar ya sea que tiene descuento o no a la interfaz
            totalapagar.setText(Double.toString(tp));
            productoComprado.add(GuiPrincipal.controlador.buscarProducto(codigo.getSelectedItem().toString()));//Este arraylist se va a llenar en base a los productos que se compren
            unidadesCompradas.add(unidades.getText());// este arraylist se llena en base a las unidades que se compren de cada producto
            setDatos();//actualiza la informacion de la tabla
        }
        //generar la advertencia de pocas unidades
        if (GuiPrincipal.controlador.restaUnidades(Integer.parseInt(unidades.getText()),codigo.getSelectedItem().toString())<=0){
            JOptionPane.showMessageDialog(rootPane,"Unidades insuficientes");
            facturar.setEnabled(false);
        }
        
        //Agregamos a la tabla
        //Borramos los campos del codigo del producto
        codigo.setSelectedIndex(0);
        
    }//GEN-LAST:event_registrarProductoActionPerformed

    private void facturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturarActionPerformed
        Cliente c;
        c=GuiPrincipal.controlador.buscarCliente(id.getSelectedItem().toString());//buscamos el cliente seleccionado 
        HashMap<String,Integer>hm=new HashMap<>();//Este sera el hashmap que usaremos para crear el objeto compra
        for (int i = 0; i < productoComprado.size(); i++) {
            hm.put( productoComprado.get(i).getCodigo(), Integer.parseInt(unidadesCompradas.get(i)));//llenamos el hashmap con la informacion del arraylist de productos comprados y el de unidades compradas 
        }
        Compra com=new Compra(fecha.getText(),c,hm,t,tp);//Crear el objeto compra
        String codigoCambio="";
        int unidadesRestar;
        for (int i = 0; i < unidadesCompradas.size(); i++) {
            codigoCambio=GuiPrincipal.controlador.getArregloProductos().get(i).getCodigo();
            unidadesRestar=Integer.parseInt(unidadesCompradas.get(i));
            GuiPrincipal.controlador.actualizarUnidades(codigoCambio,unidadesRestar);//Este metodo se utiliza para actualizar la cantidad de unidades disponibles, restando las que se acaban de comprar
        }
        //Guardar compra
        GuiPrincipal.controlador.guardarCompras(com);//se lleva el objeto compra al arraylist
        //Limpiar toda la interfaz
        fecha.setText(null);
        fecha.setEditable(true);
        id.setSelectedIndex(0);
        id.setEditable(true);
        codigo.setSelectedIndex(0);
        total.setText(null);
        totalapagar.setText(null);
        unidades.setText(null);
        //limpiar variables estaticas
        t=0;
        tp=0;
        mtablas.setRowCount(0);//limpiar la tabla
        //Limpiar el arraylist de compras
        productoComprado.clear();
        unidadesCompradas.clear();
        
    }//GEN-LAST:event_facturarActionPerformed

    private void cancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCompraActionPerformed
        //Limpiar toda la interfaz
        fecha.setText(null);
        fecha.setEditable(true);
        id.setSelectedIndex(0);
        id.setEditable(true);
        codigo.setSelectedIndex(0);
        total.setText(null);
        totalapagar.setText(null);
        unidades.setText(null);
        //limpiar variables estaticas
        t=0;
        tp=0;
    }//GEN-LAST:event_cancelarCompraActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarCompra;
    private javax.swing.JComboBox<String> codigo;
    private javax.swing.JButton facturar;
    private javax.swing.JTextField fecha;
    private javax.swing.JComboBox<String> id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mtabla;
    private javax.swing.JButton registrarProducto;
    private javax.swing.JTextField total;
    private javax.swing.JTextField totalapagar;
    private javax.swing.JTextField unidades;
    // End of variables declaration//GEN-END:variables
}
