/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectologica2;

import javax.swing.JOptionPane;

/**
 *
 * @author 27sin
 */
public class GuiProducto extends javax.swing.JFrame {

    /**
     * Creates new form GuiProducto
     */
    public GuiProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resolucion = new javax.swing.ButtonGroup();
        tipo = new javax.swing.ButtonGroup();
        uso = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        referencia = new javax.swing.JTextField();
        marca = new javax.swing.JComboBox<>();
        color = new javax.swing.JTextField();
        hd = new javax.swing.JRadioButton();
        fullhd = new javax.swing.JRadioButton();
        precio = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        televisor = new javax.swing.JRadioButton();
        proyector = new javax.swing.JRadioButton();
        labeltamaño = new javax.swing.JLabel();
        tamaño = new javax.swing.JComboBox<>();
        labeltipopantalla = new javax.swing.JLabel();
        tipopantalla = new javax.swing.JComboBox<>();
        labelos = new javax.swing.JLabel();
        os = new javax.swing.JComboBox<>();
        labeltipouso = new javax.swing.JLabel();
        hogar = new javax.swing.JRadioButton();
        empresarial = new javax.swing.JRadioButton();
        labelvisualizacion = new javax.swing.JLabel();
        visualizacion = new javax.swing.JComboBox<>();
        guardar = new javax.swing.JButton();
        Mostrar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Registro de productos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Codigo del producto:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Referencia del producto:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Marca:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Color:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Resolucion:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio: ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cantidad disponible");

        marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Samsung", "Kelly", "LG" }));

        resolucion.add(hd);
        hd.setForeground(new java.awt.Color(255, 255, 255));
        hd.setText("HD");
        hd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hdActionPerformed(evt);
            }
        });

        resolucion.add(fullhd);
        fullhd.setForeground(new java.awt.Color(242, 242, 242));
        fullhd.setText("FULL HD\n");
        fullhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullhdActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("Tipo:");

        tipo.add(televisor);
        televisor.setForeground(new java.awt.Color(242, 242, 242));
        televisor.setText("Televisor");
        televisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                televisorActionPerformed(evt);
            }
        });

        tipo.add(proyector);
        proyector.setForeground(new java.awt.Color(242, 242, 242));
        proyector.setText("Proyector");
        proyector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proyectorActionPerformed(evt);
            }
        });

        labeltamaño.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labeltamaño.setForeground(new java.awt.Color(242, 242, 242));
        labeltamaño.setText("Tamaño de la pantalla:");
        labeltamaño.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10/32", "40/49", "50/59", "60/75", "76+" }));
        tamaño.setEnabled(false);

        labeltipopantalla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labeltipopantalla.setForeground(new java.awt.Color(242, 242, 242));
        labeltipopantalla.setText("Tipo de pantalla:");

        tipopantalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LED", "Nanocell", "OLED", "QLED", "MiniLED", "QNED", " ", " " }));
        tipopantalla.setEnabled(false);

        labelos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelos.setForeground(new java.awt.Color(255, 255, 255));
        labelos.setText("Sistema operativo:");

        os.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Android TV", "Google TV", "Tizen", "Web OS", "Roku TV" }));
        os.setEnabled(false);

        labeltipouso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labeltipouso.setForeground(new java.awt.Color(242, 242, 242));
        labeltipouso.setText("Tipo de Uso: ");

        hogar.setForeground(new java.awt.Color(242, 242, 242));
        hogar.setText("Hogar");
        hogar.setEnabled(false);

        empresarial.setForeground(new java.awt.Color(242, 242, 242));
        empresarial.setText("Empresarial");
        empresarial.setEnabled(false);
        empresarial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresarialActionPerformed(evt);
            }
        });

        labelvisualizacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelvisualizacion.setForeground(new java.awt.Color(242, 242, 242));
        labelvisualizacion.setText("Tecnologia de Visualizacion:");

        visualizacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LCD", "LED", "DLPP" }));
        visualizacion.setEnabled(false);

        guardar.setText("Guardar");
        guardar.setEnabled(false);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        Mostrar.setText("Mostrar Productos\n");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labeltamaño)
                                    .addComponent(labeltipopantalla)
                                    .addComponent(labeltipouso)
                                    .addComponent(labelvisualizacion)
                                    .addComponent(labelos))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tamaño, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tipopantalla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(os, 0, 241, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(hogar)
                                        .addGap(32, 32, 32)
                                        .addComponent(empresarial))
                                    .addComponent(visualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Mostrar)
                                .addGap(18, 18, 18)
                                .addComponent(guardar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hd)
                                .addGap(27, 27, 27)
                                .addComponent(fullhd))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cantidad))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(precio))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(color))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(marca, 0, 218, Short.MAX_VALUE)
                                        .addComponent(referencia)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(televisor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(proyector))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeltamaño)
                    .addComponent(tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(referencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeltipopantalla)
                    .addComponent(tipopantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelos)
                    .addComponent(os, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hd)
                    .addComponent(fullhd)
                    .addComponent(labeltipouso)
                    .addComponent(hogar)
                    .addComponent(empresarial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelvisualizacion)
                    .addComponent(visualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardar)
                    .addComponent(Mostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(televisor)
                    .addComponent(proyector))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void televisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_televisorActionPerformed
        //Comportamiento del boton Televisor, activa los componentes del registro de productos tipo televisor para su edicion
        tamaño.setEnabled(true);
        tipopantalla.setEnabled(true);
        os.setEnabled(true);
        hogar.setEnabled(false);
        empresarial.setEnabled(false);
        visualizacion.setEnabled(false);
        guardar.setEnabled(true);
    }//GEN-LAST:event_televisorActionPerformed

    private void hdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hdActionPerformed
        
    }//GEN-LAST:event_hdActionPerformed

    private void empresarialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresarialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresarialActionPerformed

    private void proyectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proyectorActionPerformed
        //Comportamiento del boton Televisor, activa los componentes del registro de productos tipo televisor para su edicion
        tamaño.setEnabled(false);
        tipopantalla.setEnabled(false);
        os.setEnabled(false);
        hogar.setEnabled(true);
        empresarial.setEnabled(true);
        visualizacion.setEnabled(true);
        guardar.setEnabled(true);
    }//GEN-LAST:event_proyectorActionPerformed

    private void fullhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullhdActionPerformed
        
    }//GEN-LAST:event_fullhdActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        //Conseguir el valor de la resolucion en base a los botones radiales precionados
        String resolucionf="";
        if (hd.isSelected()){
           resolucionf="HD";
        }
        if (fullhd.isSelected()){
           resolucionf="Full HD";
        }
        //En base al boton radial precionado, generada un objteto tipo televisor o proyector
        if (televisor.isSelected()){
            GuiPrincipal.controlador.guardarProducto(new Televisor(tamaño.getSelectedItem().toString(),tipopantalla.getSelectedItem().toString(), os.getSelectedItem().toString(),codigo.getText(),referencia.getText(), marca.getSelectedItem().toString(),color.getText(),resolucionf,Integer.parseInt(precio.getText()),Integer.parseInt(cantidad.getText())));
        }
        if (proyector.isSelected()){
            String usof="";
            if (hogar.isSelected()){
                usof="Hogar";
            }
            if (empresarial.isSelected()){
                usof="Empresarial";
            }
            GuiPrincipal.controlador.guardarProducto(new Proyector(usof,visualizacion.getSelectedItem().toString(),codigo.getText(),referencia.getText(), marca.getSelectedItem().toString(),color.getText(),resolucionf,Integer.parseInt(precio.getText()),Integer.parseInt(cantidad.getText())));
            }
        //Mensaje de confirmacion
        JOptionPane.showMessageDialog(rootPane,"Se registro el producto");
        //Borramos todo
        tamaño.setSelectedIndex(0);
        tipopantalla.setSelectedIndex(0);
        os.setSelectedIndex(0);
        codigo.setText(null);
        referencia.setText(null);
        marca.setSelectedIndex(0);
        color.setText(null);
        resolucion.clearSelection();
        precio.setText(null);
        cantidad.setText(null);
        tipo.clearSelection();
        uso.clearSelection();
        visualizacion.setSelectedIndex(1);
        
    }//GEN-LAST:event_guardarActionPerformed

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        JOptionPane.showMessageDialog(rootPane, GuiPrincipal.controlador.getArregloProductos().toString());
    }//GEN-LAST:event_MostrarActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mostrar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField color;
    private javax.swing.JRadioButton empresarial;
    private javax.swing.JRadioButton fullhd;
    private javax.swing.JButton guardar;
    private javax.swing.JRadioButton hd;
    private javax.swing.JRadioButton hogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelos;
    private javax.swing.JLabel labeltamaño;
    private javax.swing.JLabel labeltipopantalla;
    private javax.swing.JLabel labeltipouso;
    private javax.swing.JLabel labelvisualizacion;
    private javax.swing.JComboBox<String> marca;
    private javax.swing.JComboBox<String> os;
    private javax.swing.JTextField precio;
    private javax.swing.JRadioButton proyector;
    private javax.swing.JTextField referencia;
    private javax.swing.ButtonGroup resolucion;
    private javax.swing.JComboBox<String> tamaño;
    private javax.swing.JRadioButton televisor;
    private javax.swing.ButtonGroup tipo;
    private javax.swing.JComboBox<String> tipopantalla;
    private javax.swing.ButtonGroup uso;
    private javax.swing.JComboBox<String> visualizacion;
    // End of variables declaration//GEN-END:variables
}
