package proyectologica2;

import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
public class GuiPrincipal extends javax.swing.JFrame {
    
    
    static Controlador controlador=new Controlador();
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GuiPrincipal.class.getName());

    /**
     * Creates new form guiprincipal
     */
    public GuiPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        porcentajeTelevisor = new javax.swing.JButton();
        promedioSamsung = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totalProductos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cantidadMarca = new javax.swing.JButton();
        cantidadResolucion = new javax.swing.JButton();
        cantidadTipo = new javax.swing.JButton();
        mostrarProductoCaro = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        registrarproducto = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tienda");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¡BIENVENIDO!");

        porcentajeTelevisor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        porcentajeTelevisor.setText("Porcentaje de productos televisor registrados");
        porcentajeTelevisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentajeTelevisorActionPerformed(evt);
            }
        });

        promedioSamsung.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        promedioSamsung.setText("Promedio Productos Marca Samsung");
        promedioSamsung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promedioSamsungActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Acualmente la tienda ofrece y permite registrar dos tipos de productos: ");

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Funciones:");

        totalProductos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalProductos.setText("Total de Productos en stock");
        totalProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalProductosActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("*Televisores");

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("*Proyectores");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Generar Graficos");

        cantidadMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantidadMarca.setText("Grafico de cantidad por marca\n");
        cantidadMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadMarcaActionPerformed(evt);
            }
        });

        cantidadResolucion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantidadResolucion.setText("Grafico de cantidad por resolucion\n\n");
        cantidadResolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadResolucionActionPerformed(evt);
            }
        });

        cantidadTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantidadTipo.setText("Grafico de cantidad por Tipo");
        cantidadTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadTipoActionPerformed(evt);
            }
        });

        mostrarProductoCaro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mostrarProductoCaro.setText("Mostrar el producto mas caro");
        mostrarProductoCaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarProductoCaroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(588, 588, 588)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(totalProductos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(porcentajeTelevisor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(promedioSamsung, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mostrarProductoCaro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(112, 112, 112)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cantidadResolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cantidadMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(cantidadTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))))
                .addGap(156, 501, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(promedioSamsung)
                    .addComponent(cantidadMarca))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(porcentajeTelevisor)
                    .addComponent(cantidadResolucion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalProductos)
                    .addComponent(cantidadTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mostrarProductoCaro)
                .addGap(404, 404, 404))
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        jMenu1.setBackground(new java.awt.Color(204, 204, 204));
        jMenu1.setText("Registros");

        jMenuItem2.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItem2.setText("Registrar Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        registrarproducto.setText("Registrar Productos");
        registrarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarproductoActionPerformed(evt);
            }
        });
        jMenu1.add(registrarproducto);

        jMenuItem3.setText("Registrar Compras");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new GuiCliente().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void registrarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarproductoActionPerformed
        new GuiProducto().setVisible(true);
    }//GEN-LAST:event_registrarproductoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new GuiCompra().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void porcentajeTelevisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentajeTelevisorActionPerformed
        double por;
        int canttele=controlador.cantidadTelevisores();
        int cantproduc=controlador.getArregloProductos().size();
        if(cantproduc!=0){
            por=(canttele*100)/cantproduc;
            JOptionPane.showMessageDialog(rootPane, "El porcentaje de televisores en la tienda es "+por+"%");
        }else{
            JOptionPane.showMessageDialog(rootPane, "No hay Productos registrados");
        }
    }//GEN-LAST:event_porcentajeTelevisorActionPerformed

    private void promedioSamsungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promedioSamsungActionPerformed
        if(controlador.cantidadSamsung()!=0){
            double prom;
            prom=controlador.PromedioPrecioSamsung();
            JOptionPane.showMessageDialog(rootPane, "El promedio del precio de productos marca Samsung es: "+prom);
        }else{
            JOptionPane.showMessageDialog(rootPane, "No hay productos marca Samsung registrados");
        }
    }//GEN-LAST:event_promedioSamsungActionPerformed

    private void totalProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalProductosActionPerformed
        int cantidadtele;
        int cantidadproyec;
        int cantidadprodu;
        cantidadtele=controlador.cantidadTelevisores();
        cantidadproyec=controlador.cantidadProyectores();
        cantidadprodu=controlador.getArregloProductos().size();
        JOptionPane.showMessageDialog(rootPane, "Actualmente hay "+cantidadtele+" televisores registrados.\n\nActualmente hay "+cantidadproyec+" proyectores registrados.\n\nPara un total de "+cantidadprodu+" productos registrados");
    }//GEN-LAST:event_totalProductosActionPerformed

    private void cantidadMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadMarcaActionPerformed
        
        DefaultPieDataset data = new DefaultPieDataset();//Se crea un objeto tipo piedataset, que se encarga de almacenar los datos que se mostarar en el grafico
        data.setValue("Sumsung",controlador.cantidadSamsung());//Se crean los valores, con una etiqueta tipo string y un metodo que devuelve la cantidad buscada
        data.setValue("Kelly", controlador.cantidadKelly());
        data.setValue("LG", controlador.cantidadLG());
        
        JFreeChart chart = ChartFactory.createPieChart(
         "Grafico de cantidad por Marcas", //Titulo del grafico
         data, //se cargan los datos en el grafico
         true, //funcion de mostrar leyendas
         true, //usar tooltips (informacion emergente
         false);//generar URLs, no se utiliza en aplicaciones locales
        
        ChartFrame frame = new ChartFrame("JFreeChart", chart);//Crea una venta tipo ChartFrame, que mostrara el grafico
        frame.pack();//ajusta el tamaño del grafico a la ventana 
        frame.setVisible(true);//lo hace visible
    }//GEN-LAST:event_cantidadMarcaActionPerformed

    private void cantidadResolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadResolucionActionPerformed
        DefaultPieDataset data= new DefaultPieDataset();
        data.setValue("HD",controlador.cantidadHD());
        data.setValue("Full HD",controlador.cantidadFullHD());
        
        JFreeChart chart = ChartFactory.createPieChart(
         "Grafico de cantidad por resolucion", 
         data, 
         true, 
         true, 
         false);
        
        ChartFrame frame = new ChartFrame("JFreeChart", chart);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_cantidadResolucionActionPerformed

    private void cantidadTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadTipoActionPerformed
        DefaultPieDataset data = new DefaultPieDataset();
        data.setValue("Televisores",controlador.cantidadTelevisores());
        data.setValue("proyectores", controlador.cantidadProyectores());
        
        JFreeChart chart = ChartFactory.createPieChart(
         "Grafico de cantidad por Tipo de producto", 
         data, 
         true, 
         true, 
         false);
        
        ChartFrame frame = new ChartFrame("JFreeChart", chart);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_cantidadTipoActionPerformed

    private void mostrarProductoCaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarProductoCaroActionPerformed
        JOptionPane.showMessageDialog(rootPane,"El producto mas caro es: \n"+controlador.buscarProductoCaro().toString());
    }//GEN-LAST:event_mostrarProductoCaroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GuiPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cantidadMarca;
    private javax.swing.JButton cantidadResolucion;
    private javax.swing.JButton cantidadTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mostrarProductoCaro;
    private javax.swing.JButton porcentajeTelevisor;
    private javax.swing.JButton promedioSamsung;
    private javax.swing.JMenuItem registrarproducto;
    private javax.swing.JButton totalProductos;
    // End of variables declaration//GEN-END:variables
}
